## YAML Template.
---

- name: GET STRUCTURED DATA BACK FROM CLI DEVICES
  hosts: ciscors
  strategy: debug
  connection: local
  gather_facts: false
  
  
  vars:
    cli:  
        ciscoios: 'ciscors'
        ciscoiosssh: 'ciscors_ssh'
        localfile: 'C:/Users/sg05477/GNS3/images/IOS.bin'
        remotefile: 'c7200-advipservicesk9-mz.152-4.S5.bin'

  tasks:
   -  name: Show ip interface brief in JSON
      ntc_show_command:
        connection: ssh
        template_dir: "/home/samya/s2svpn/PlaybookwithNTC/ntc-ansible/ntc-templates/templates"
        platform: cisco_ios
        command: show ip interface brief in JSON
        host: "{{ inventory_hostname }}"  
        username: "{{ user }}"
        password: "{{ pass }}"
        secret: "{{ secret }}"
      register: result
      
   - debug: var=hostvars[inventory_hostname]
   #- debug: var=result.response[user]
   #- debug: var=result.response.stdout
   #- debug:
       #msg: "hallo {{ inventory_hostname }}"
     
   #- name: Save running-configuration to specified remote file
    # ntc_save_config:
     #  platform:  cisco_ios_ssh
      # remote_file: "/home/samya/s2svpn/PlaybookwithNTC/output/running.cfg"
       #host: "{{ inventory_hostname }}"
       #u#sername: "{{ user }}"
       #password: "{{ pass }}"
       #secret: "{{ secret }}"

   #- debug: var=hostvars[inventory_hostname]['user']
   
   #- debug: var=result.stdout

   - name: Save running-configuration to specified remote file
     ntc_save_config:
       platform: cisco_ios
       connection: ssh
       template_dir: "/home/samya/s2svpn/PlaybookwithNTC/ntc-ansible/ntc-templates/templates"
       remote_file: "running.cfg"
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       secret: "{{ secret }}"
   - debug: var=hostvars[inventory_hostname]       