## YAML Template.
---
- hosts: ciscors
  connection: local
  gather_facts: true

  vars:
    provider:
      username: admin
      password: admin
      

  tasks:
  - name: Show ip interface brief in JSON
    ntc_show_command:
      provider: "{{ provider }}"
      connection: ssh
      template_dir: "/home/samya/s2svpn/PlaybookwithNTC/ntc-ansible/ntc-templates/templates"
      command: "{{ item }}"
      secret: "{{ secret }}"
    with_items:
      - "{{ command }}"
    register: results

  - name: Clean loop output
    set_fact:
      clean_out: "{{ clean_out|default([]) + [item.response] }}"
    with_items:
      - "{{ results.results }}"
    no_log: True

  - name: Display information from 'show' output
    debug: msg="{{ clean_out }}"
    tags: DEBUG