## YAML Template.
---
- hosts: ciscors
  connection: local
  gather_facts: true

  vars:
    cli:
        username: "{{ user }}"
        password: "{{ pass }}"
        secret: "{{ secret }}"
        ciscoios: 'ciscors'
        ciscoiosssh: 'ciscors_ssh'
        localfile: 'C:/Users/sg05477/GNS3/images/IOS.bin'
        remotefile: 'c7200-advipservicesk9-mz.152-4.S5.bin'
        transport: cli

  tasks:
    - name: Configure VPN
      ios_config:
        provider: "{{ cli }}"   
        lines:           
          - crypto isakmp policy 10
          #- hash md5
          - authentication pre-share
          - encryption 3des
          - group 2
          - hash md5
          - lifetime 86400
          - exit
          - crypto isakmp key 0 admin address 192.168.3.12
          - crypto ipsec transform-set MYTRANS2 esp-3des esp-sha-hmac
          - exit
          - access-list 100 permit icmp any any
          - crypto map MYMAP2 10 ipsec-isakmp
          - match address 100
          - set peer 192.168.3.12
          - set pfs group2
          - set transform-set MYTRANS2
          - set security-association lifetime seconds 86400
          - exit
          - interface GigabitEthernet 3/0
          - crypto map MYMAP2
          - end
        
        
    - name: Verify Configurations
      ios_command:
        commands:
          - show crypto ipsec sa
        provider: "{{ cli }}" 
      register: config
      
    - name: save output to /home/samya/s2svpn/ConfigurationTask/VPN
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "/home/samya/s2svpn/ConfigurationTask/VPN/VPN_details{{ inventory_hostname }}.txt"
        
            
