## YAML Template.
## YAML Template.
---
- hosts: ciscors
  connection: local
  gather_facts: false

  vars:
    cli:
        username: "{{ user }}"
        password: "{{ pass }}"
        secret: "{{ secret }}"
        ciscoios: 'ciscors'
        ciscoiosssh: 'ciscors_ssh'
        localfile: 'C:/Users/sg05477/GNS3/images/IOS.bin'
        remotefile: 'c7200-advipservicesk9-mz.152-4.S5.bin'
        transport: cli

  tasks:
      
    - debug:
        msg : "1: {{ user }}" 
    - debug:
        msg : "2: {{ pass }}"
    - debug:
        msg : "3: {{ secret }}"
    - name: Configure VPN R1R2
      ignore_errors: no
      ios_config:
        #authorize: yes  
        provider: "{{ cli }}"        
        lines:            
          - crypto isakmp policy 16
          #- hash md5
          - authentication pre-share
          - encryption 3des
          - group 2
          - hash md5
          - lifetime 86400
          - exit
          - crypto isakmp key 0 admin address 192.168.1.11
          - crypto ipsec transform-set TRANS esp-3des esp-sha-hmac
          - exit
          - access-list 102 permit icmp any any
          - crypto map MYMAP 16 ipsec-isakmp
          - match address 102
          - set peer 192.168.1.11
          - set pfs group2
          - set transform-set TRANS
          - set security-association lifetime seconds 86400
          - exit
          #- interface range GigabitEthernet1/0/2-20
          - interface GigabitEthernet 4/0
          - crypto map MYMAP
          - end
        #parents: crypto isakmp policy11
        #authorize: yes
