## YAML Template.
---

- name: Run IOS Commands on remote devices
  hosts: ciscors
  connection: local
  gather_facts: True

  vars:
    cli:
        host: "{{ inventory_hostname }}"
        username: "{{ user }}"
        password: "{{ pass }}"
        transport: cli
        
    run_commands:
      - sh clock
      - sh run
      - sh version
      - sh cdp nei
      - sh proc cpu history
      - sh ip protocols
      - sh ip route
      - sh ntp status
      - sh logging

  tasks:
    - name: Run commands
      ios_command:
        commands: "{{run_commands}}"
        provider: "{{ cli }}"
        interval: 10
        
      # Save the output to a file  
      register: output
    - local_action: copy content="{{ output.stdout }}" dest="/home/samya/s2svpn/s2soutput/Runningconfigoutput/output.txt"
    - local_action: copy content="{{ output.stdout }}" dest="/home/samya/s2svpn/s2soutput/Runningconfigoutput/output.doc"
    



